### PR TITLE
Update page.html

### PR DESCRIPTION
**Pull request by iamstarkov**
обновил ссылку на себя

### CODE REVIEW

**Comment by A** [comment]
thx)

**Comment by iamstarkov** [comment]
i don’t remember how to publish =( can you do it for me?

**Comment by A** [comment]
oh, shi... It's just terrible 'cause me too :(

**Comment by A** [comment]
Yay, this is regular github pages. What are you talking about :DD

**Comment by iamstarkov** [comment]
sorry, im dumb today

**Pull request merged**
