### PR TITLE
fix rss link

### PR DESCRIPTION
**Pull request by yetithefoot**

### CODE REVIEW

**Comment by yetithefoot** [comment]
FYI, I tried to add atom to **https://ifttt.com**, but it said that link is broken. =(
Validators found few warnings: **title** is missing and **location** is broken

http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Flargescalejs.ru%2Fatom.xml
http://www.validome.org/rss-atom/validate?lang=en&url=http://largescalejs.ru/atom.xml&versi
on=atom_1_0
http://www.rssboard.org/rss-validator/check.cgi?url=http%3A%2F%2Flargescalejs.ru%2Fatom.xml

**Comment by A** [comment]
Awesome! Thank You!

**Comment by yetithefoot** [comment]
@shuvalov-anton Looks like you have to fix **{{ site.production_url }}** cause it links to another domain.

**Comment by iamstarkov** [comment]
Done!

**Pull request merged**
